# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 11 Mar 2016 15:54:17 +0000
*               @ALL          0
*               @user         8
